using Billy.Api.Utils;
using System.Text.Json.Serialization;

namespace Billy.Api.Models
{

    /// <summary>
    /// API response envelope for bank payment endpoints
    /// (<c>GET /v2/bankPayments</c>, <c>POST /v2/bankPayments</c>, etc.).
    /// </summary>
    public class BankPaymentRoot : Root
    {
        /// <summary>Single bank payment returned by a Get request.</summary>
        public BankPayment? BankPayment { get; set; }

        /// <summary>List of bank payments returned by a List or Create request.</summary>
        public List<BankPayment>? BankPayments { get; set; }
    }

    /// <summary>
    /// Represents a bank or cash payment in Billy. Creating a bank payment with subject associations
    /// marks the linked invoices or bills as paid and posts the corresponding ledger entries.
    /// Use the <see cref="Actions.BankPaymentActions"/> extension methods for convenient payment helpers.
    /// </summary>
    public class BankPayment : IEntity
    {
        /// <summary>Unique identifier assigned by the Billy API.</summary>
        public string? Id { get; set; }

        /// <summary>ID of the organization this payment belongs to.</summary>
        public string OrganizationId { get; set; }

        /// <summary>ID of the <see cref="Contact"/> (customer or supplier) involved in this payment.</summary>
        public string? ContactId { get; set; }

        /// <summary>Timestamp when the bank payment was created. Server-assigned; read-only.</summary>
        [JsonIgnoreOnWrite]
        public DateTime CreatedTime { get; set; }

        /// <summary>Value date of the payment (date-only, serialized as <c>yyyy-MM-dd</c>).</summary>
        public DateOnly EntryDate { get; set; }

        /// <summary>Payment amount in the bank account's currency.</summary>
        public decimal CashAmount { get; set; }

        /// <summary>
        /// Direction of the cash flow relative to the bank account.
        /// Use <see cref="CashSide.Debit"/> for incoming payments (invoice receipts)
        /// and <see cref="CashSide.Credit"/> for outgoing payments (bill settlements).
        /// </summary>
        public CashSide? CashSide { get; set; }

        /// <summary>ID of the bank or cash <see cref="Account"/> that receives or disburses the funds.</summary>
        public string CashAccountId { get; set; }

        /// <summary>
        /// Exchange rate between the bank account currency and the subject currency,
        /// when the payment involves a foreign currency invoice or bill.
        /// </summary>
        public decimal? CashExchangeRate { get; set; }

        /// <summary>
        /// ISO 4217 currency code of the invoice or bill being settled,
        /// when it differs from the bank account currency.
        /// </summary>
        public string? SubjectCurrencyId { get; set; }

        /// <summary>Bank fee charged for this transaction, in the bank account's currency.</summary>
        public decimal? FeeAmount { get; set; }

        /// <summary>ID of the <see cref="Account"/> to which the bank fee is posted.</summary>
        public string? FeeAccountId { get; set; }

        /// <summary><c>true</c> if the payment has been voided and its postings reversed.</summary>
        public bool? IsVoided { get; set; }

        /// <summary>
        /// Links to the invoices or bills settled by this payment.
        /// Each entry uses the format <c>"invoice:&lt;id&gt;"</c> or <c>"bill:&lt;id&gt;"</c>.
        /// </summary>
        public List<BankPaymentAssociation>? Associations { get; set; }

        /// <summary>
        /// Contact balance postings generated by this payment. Server-assigned; read-only.
        /// </summary>
        [JsonIgnoreOnWrite]
        public List<BankPaymentContactBalancePosting>? ContactBalancePostings { get; set; }
    }

    /// <summary>
    /// Links a <see cref="BankPayment"/> to an invoice or bill, causing the referenced document
    /// to be marked as paid when the payment is created.
    /// </summary>
    public class BankPaymentAssociation
    {
        /// <summary>
        /// Reference to the document being settled, in the format <c>"invoice:&lt;id&gt;"</c>
        /// or <c>"bill:&lt;id&gt;"</c>.
        /// </summary>
        public string? SubjectReference { get; set; }
    }

    /// <summary>
    /// A ledger posting to a contact's balance account generated as part of a <see cref="BankPayment"/>.
    /// Returned read-only in the API response.
    /// </summary>
    public class BankPaymentContactBalancePosting
    {
        /// <summary>Unique identifier of this balance posting.</summary>
        public string? Id { get; set; }

        /// <summary>ID of the <see cref="Contact"/> whose balance is affected.</summary>
        public string? ContactId { get; set; }

        /// <summary>ISO 4217 currency code of this posting.</summary>
        public string? CurrencyId { get; set; }

        /// <summary>Monetary amount of this posting.</summary>
        public decimal? Amount { get; set; }

        /// <summary>Whether this is a <c>"Debit"</c> or <c>"Credit"</c> posting.</summary>
        public CashSide? Side { get; set; }
    }
}
